### ISSUE TITLE
Minor improvements

### ISSUE THREAD

**Issue by Narvet** [jsloop42/BookmarksOrganizer#1]
Hey, 
By looking in the overview on the chrome webstore I thought i'd have some kind of an organizer interface, but apparently no, these are screenshots. And I thought that to access it I needed to click the (only) "reorder" button and that it would take me there. But it did not :(
So maybe add a little description on the webstore if you can, saying exaclty what it does : ONLY sort bookmarks by alphabetical.
Also making the ordering by alphabetical reversible would be great, so no one ever has to spend 30mins again reorganizing the whole thing. 
And also prompting the user when clicking that stuff will be organize by alphabetical would be neat, preventing all of the mess that can follow.
Finally rename that "reorder" button to something more precise, like "order bookmarks by alphabetical".

**Comment by jaseemtan** [comment]
I have updated the store description specifying 'Sort Bookmarks Alphabetically' with v4.0.0. Thanks.
